import = [
  # Install catppuccin macchiato (https://github.com/catppuccin/alacritty)
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[shell] 
program = "/usr/bin/env"
args = ["zsh"]

# Yoinked from the arch wiki
[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
